import dotenv from 'dotenv';

dotenv.config();

interface Config {
  PORT: number;
  NODE_ENV: string;
  SUPABASE_URL: string;
  SUPABASE_PUBLISHABLE_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  DATABASE_URL: string;
  DATABASE_INTROSPECT_URL: string;
  AUTHORIZED_CALLER: string;
  ANIMALS_MICROSERVICE_REHOMER_BASE_URL: string;
  MESSAGES_MICROSERVICE_BASE_URL: string;
}

const config: Config = {
  PORT: +process.env.PORT!,
  NODE_ENV: process.env.NODE_ENV!,
  SUPABASE_URL: process.env.SUPABASE_URL!,
  SUPABASE_PUBLISHABLE_KEY: process.env.SUPABASE_PUBLISHABLE_KEY!,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY!,
  DATABASE_URL: process.env.DATABASE_URL!,
  DATABASE_INTROSPECT_URL: process.env.DATABASE_INTROSPECT_URL!,
  AUTHORIZED_CALLER: process.env.AUTHORIZED_CALLER!,
  ANIMALS_MICROSERVICE_REHOMER_BASE_URL:
    process.env.ANIMALS_MICROSERVICE_REHOMER_BASE_URL!,
  MESSAGES_MICROSERVICE_BASE_URL: process.env.MESSAGES_MICROSERVICE_BASE_URL!
};

export default config;
